name: labetova_lab_2
description: A new Flutter project.

publish_to: 'none' 

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true
